import logo from "../../assets/Logo.png"
export const TraksTabInform=[
    {id:"1" ,TabTitle:"#01",ContentTitle:"TRACK#1 - 病人基本資料",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"2" ,TabTitle:"#02",ContentTitle:"TRACK#2 - 生理量測資訊",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"3" ,TabTitle:"#03",ContentTitle:"TRACK#3 - 處方用藥及文件打包",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"4" ,TabTitle:"#04",ContentTitle:"TRACK#4 - 醫學影像與病理",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"5" ,TabTitle:"#05",ContentTitle:"TRACK#5 - 偕同照護",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"6" ,TabTitle:"#06",ContentTitle:"TRACK#6 - 基因體標記",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"7" ,TabTitle:"#07",ContentTitle:"TRACK#7 - 緊急醫療救護",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"8" ,TabTitle:"#08",ContentTitle:"TRACK#8 - 醫療保險",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"9" ,TabTitle:"#09",ContentTitle:"TRACK#9 - 遠距醫療",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
    {id:"10" ,TabTitle:"#10",ContentTitle:"TRACK#10 - 癌症登記",Img:[{"id":"1","img":logo},{"id":"2","img":logo},{"id":"3","img":logo}],List:[{"id":"1","Sc":"Scenario 1 病人身分確認用"}, {"id":"2","Sc":"Scenario 2 聯繫病人用 "},{"id":"3","Sc":"Scenario 3：院外系統 "},{"id":"4","Sc":"Scenario 4 (2022已移除，整併進Track #7緊急醫療救護) "}],Sc1:<div><img src={logo}/></div>,},
]